### PR TITLE
Code highlight

### LINKED ISSUE #34: Code highlighter does not work
Currently, we try to get the output of marked and then color the code blocks using Atom text editor (which is complicated and does not work), while the better approach is to provide `highlight` option to marked.

Using a code similar to the following we can use marked's highlight option.

```js
marked.setOptions({
  highlight: function(code, lang, callback) {
    let scopeName = scopeForFenceName(lang) // our util funciton
    highlight(code, scopeName).then((codeResult) => {
      callback?.(null, codeResult.join("\n"))
    })
  }
});
```

```js
/**
 * Highlights the given code with the given scope name (language)
 * @param code the given code as string
 * @param scopeName the language to highlight the code for
 */
export async function highlight(code: string, scopeName: string) {
  const ed = new TextEditor({
    readonly: true,
    keyboardInputEnabled: false,
    showInvisibles: false,
    tabLength: atom.config.get("editor.tabLength"),
  })
  const el = atom.views.getView(ed)
  try {
    el.setUpdatedSynchronously(true)
    el.style.pointerEvents = "none"
    el.style.position = "absolute"
    el.style.top = "100vh"
    el.style.width = "100vw"
    atom.grammars.assignLanguageMode(ed.getBuffer(), scopeName)
    ed.setText(code)
    ed.scrollToBufferPosition(ed.getBuffer().getEndPosition())
    atom.views.getView(atom.workspace).appendChild(el)
    await editorTokenized(ed)
    return Array.from(el.querySelectorAll(".line:not(.dummy)")).map((x) => x.innerHTML)
  } finally {
    el.remove()
  }
}

/**
 * A function that resolves once the given editor has tokenized
 * @param editor
 */
export async function editorTokenized(editor: TextEditor) {
  return new Promise((resolve) => {
    const languageMode = editor.getBuffer().getLanguageMode()
    const nextUpdatePromise = editor.component.getNextUpdatePromise()
    if ("fullyTokenized" in languageMode || "tree" in languageMode) {
      resolve(nextUpdatePromise)
    } else {
      const disp = editor.onDidTokenize(() => {
        disp.dispose()
        resolve(nextUpdatePromise)
      })
    }
  })
}
```

The issue is that I don't know how to pass the language name to marked.

cc: @UziTech

### PR DESCRIPTION
**Pull request by aminya**
Fixes #34

### CODE REVIEW

File: src/renderer.ts [hunk 1]
```diff
@@ -11,102 +11,78 @@ import marked from "marked"
...
  * renders markdown to safe HTML
  * @param  {String} markdownText the markdown text to render
+ * @param grammar scope name used for highlighting the code
  * @return {Node} the html template node containing the result
  */
-function internalRender(markdownText: string): Node {
-  let html = DOMPurify.sanitize(marked(markdownText, { breaks: true }))
+function internalRender(markdownText: string, grammar: string = "text.plain"): Node {
+  let html = marked(markdownText, {
+    highlight: function(code, lang, callback) {
```
Comment (aminya) [inline src/renderer.ts:77]: Marked never enters this function. I tried with debugger.

Comment (aminya) [reply src/renderer.ts:77]: I made a branch to use markdown instead of HTML for code snippets:
https://github.com/atom-ide-community/atom-ide-base/commit/99b722b047dad9e7b3f1292fa1e5eaca3c93d822

Comment (aminya) [reply src/renderer.ts:77]: @UziTech `callback` is undefined! I followed the example in https://marked.js.org/using_advanced#highlight. 

Doesn't marked accept async functions?

Comment (UziTech) [reply src/renderer.ts:77]: You have to call marked with a callback in order for a callback to be passed to highlighter.

```js
marked(markdown, options, callback);
```

File: src/renderer.ts [hunk 2]
```diff
@@ -11,102 +11,77 @@ import marked from "marked"
...
+    await editorTokenized(ed)
+    return Array.from(el.querySelectorAll(".line:not(.dummy)")).map((x) => x.innerHTML)
+  } finally {
+    el.remove()
+  }
+}
+
+marked.setOptions({
+  breaks: true,
+  sanitizer: (html) => DOMPurify.sanitize(html),
```
Comment (UziTech) [inline src/renderer.ts:66]: sanitizer is deprecated. You should sanitize the output of marked if you want it to be safe.

Comment (UziTech) [reply src/renderer.ts:66]: for sanitizer to work you also have to pass `sanitize: true`

Comment (aminya) [reply src/renderer.ts:65]: Oh, I see. Thanks for letting me know. I can do it in our code instead.

File: src/renderer.ts (hunk 1 above)
Comment (aminya) [reply src/renderer.ts]: This is fixed now, but the code isn't that pretty 😄 I hope marked supports async functions someday.
